### ISSUE TITLE
Cairo1 contract executed failed with contract bootloader

### ISSUE THREAD

**Issue by canacechan** [Okm165/cairo1-cairo0bootloader#11]
Cairo1 contract executed failed with contract bootloader

**Reproduce steps:**
1. git clone git@github.com:canacechan/cairo1-cairo0bootloader.git
2. git checkout contracts_execute_failed
3. setup cairo_venv
4. cd contract && scarb build
5. starknet-sierra-compile target/dev/contract_HelloBootloader.contract_class.json ../bootloader_input.json ----add-pythonic-hints
6. Add a return footer at the end of the contract's bytecode (increase the bytecode segment size by one).
7. python install.py
8. python compile.py
9. python run.py

**Observation:**
Starting: Running contract in cairo0 bootloader...
Command: cairo-run         --program=bootloader.json         --layout=starknet_with_keccak         --program_input=bootloader_input.json         --air_public_input=bootloader_public_input.json         --air_private_input=bootloader_private_input.json         --trace_file=bootloader.trace         --memory_file=bootloader.memory         --print_output         --proof_mode         --print_info
/Users/zhenyuli/cairo_venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
builtin_ptrs.selectable.range_check:  19:0
contract_entry_point: 16:0
builtin_ptrs: <starkware.cairo.lang.vm.vm_consts.VmConstsReference object at 0x11de67d90>
syscall_ptr: 21:0
calldata_start: 20:0
calldata_end: 20:4
Error at pc=16:103:
Unknown value for memory cell at address 2345108766317314047.
Cairo traceback (most recent call last):
<start>:3:1: (pc=0:2)
call main;
^*******^
bootloader/contract/contract_bootloader.cairo:58:5: (pc=0:576)
cairo1-cairo0bootloader/cairo0-bootloader/bootloader/contract/run_contract_bootloader.cairo:112:39: (pc=0:548)
        let (retdata_size, retdata) = execute_entry_point(compiled_class, &execution_context);
                                      ^*****************************************************^
cairo1-cairo0bootloader/cairo0-bootloader/bootloader/contract/execute_entry_point.cairo:199:5: (pc=0:400)
    call abs contract_entry_point;
    ^***************************^
Error running command 'cairo-run         --program=bootloader.json         --layout=starknet_with_keccak         --program_input=bootloader_input.json         --air_public_input=bootloader_public_input.json         --air_private_input=bootloader_private_input.json         --trace_file=bootloader.trace         --memory_file=bootloader.memory         --print_output         --proof_mode         --print_info': Command 'cairo-run         --program=bootloader.json         --layout=starknet_with_keccak         --program_input=bootloader_input.json         --air_public_input=bootloader_public_input.json         --air_private_input=bootloader_private_input.json         --trace_file=bootloader.trace         --memory_file=bootloader.memory         --print_output         --proof_mode         --print_info' returned non-zero exit status 1.
Cheers

**Comment by Okm165** [comment]
The issue comes down to usage of `bitwise` builtin for some reason when contract uses it it fails.
Investigating issue

**Comment by canacechan** [comment]
https://github.com/Okm165/cairo1-cairo0bootloader/pull/12 I have checked this fix, it worked for bitwise builtin. Both Pedersen hash and Poseidon hash are supported. Great job, sir.
